{"uid":"51990225bd97b2a9","name":"Валидация: создание борды с именем — ожидаемый статус 400","fullName":"tests.test_backend.board.board_validation_test#test_create_board_name_validation","historyId":"79e825556c8e979fb839ef559890d9cb","time":{"start":1749744403345,"stop":1749744403679,"duration":334},"status":"passed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"delete_output_dir","time":{"start":1749744399429,"stop":1749744399429,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"_verify_url","time":{"start":1749744399429,"stop":1749744399429,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"pytestconfig","time":{"start":1749744399429,"stop":1749744399429,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"base_url","time":{"start":1749744399429,"stop":1749744399429,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"owner_client","time":{"start":1749744399429,"stop":1749744400163,"duration":734},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"temp_space","time":{"start":1749744400163,"stop":1749744401184,"duration":1021},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"temp_project","time":{"start":1749744401184,"stop":1749744402659,"duration":1475},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"testStage":{"status":"passed","steps":[{"name":"Проверка, что API вернул статус 400 при none","time":{"start":1749744403679,"stop":1749744403679,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"attachments":[{"uid":"9e32acb5427c7602","name":"stdout","source":"9e32acb5427c7602.txt","type":"text/plain","size":71}],"parameters":[],"shouldDisplayMessage":false,"stepsCount":1,"attachmentsCount":1,"hasContent":true},"afterStages":[{"name":"temp_space::0","time":{"start":1749744437355,"stop":1749744438003,"duration":648},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"labels":[{"name":"tag","value":"backend"},{"name":"parentSuite","value":"tests.test_backend.board"},{"name":"suite","value":"board_validation_test"},{"name":"host","value":"pkrvmxyh4eaekms"},{"name":"thread","value":"2515-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_backend.board.board_validation_test"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"expected_status","value":"400"},{"name":"name","value":"None"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"history":{"statistic":{"failed":0,"broken":7,"skipped":0,"passed":3,"unknown":0,"total":10},"items":[{"uid":"ca754d9884e8198d","reportUrl":"https://vaizcom.github.io/autotests/124//#testresult/ca754d9884e8198d","status":"passed","time":{"start":1749744317528,"stop":1749744317926,"duration":398}},{"uid":"84b274f944015c77","reportUrl":"https://vaizcom.github.io/autotests/123//#testresult/84b274f944015c77","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f6ed7455e50>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749744002522,"stop":1749744002522,"duration":0}},{"uid":"b17c67e0eb8cdb32","reportUrl":"https://vaizcom.github.io/autotests/122//#testresult/b17c67e0eb8cdb32","status":"passed","time":{"start":1749743621034,"stop":1749743621468,"duration":434}},{"uid":"eaad7dee95aebea1","reportUrl":"https://vaizcom.github.io/autotests/119//#testresult/eaad7dee95aebea1","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc7b5913490>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749742819672,"stop":1749742819672,"duration":0}},{"uid":"4a6abca04037463d","reportUrl":"https://vaizcom.github.io/autotests/118//#testresult/4a6abca04037463d","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f9cb88f1f10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749742667037,"stop":1749742667037,"duration":0}},{"uid":"fecbf053a7ba2918","reportUrl":"https://vaizcom.github.io/autotests/117//#testresult/fecbf053a7ba2918","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2b9f21f250>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749742496802,"stop":1749742496802,"duration":0}},{"uid":"de51bbe4cd46760e","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/de51bbe4cd46760e","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741233265,"stop":1749741233265,"duration":0}},{"uid":"ce81737bf595c70f","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/ce81737bf595c70f","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740825720,"stop":1749740825720,"duration":0}},{"uid":"8175a3373a3849e8","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/8175a3373a3849e8","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740652501,"stop":1749740652501,"duration":0}}]},"tags":["backend"]},"source":"51990225bd97b2a9.json","parameterValues":["400","None"]}