{"uid":"98c1e5824a231cdf","name":"Тест: Проверка предельной длины slug","fullName":"tests.test_backend.project.test_project#test_project_slug_too_long","historyId":"2cb76e81e4a27f4607f4f034fc6f46c4","time":{"start":1749744340243,"stop":1749744340439,"duration":196},"status":"passed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":true,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_verify_url","time":{"start":1749744310971,"stop":1749744310971,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"base_url","time":{"start":1749744310971,"stop":1749744310971,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"pytestconfig","time":{"start":1749744310972,"stop":1749744310972,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"delete_output_dir","time":{"start":1749744310972,"stop":1749744310972,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"owner_client","time":{"start":1749744310972,"stop":1749744311581,"duration":609},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"temp_space","time":{"start":1749744311581,"stop":1749744312659,"duration":1078},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"afterStages":[{"name":"temp_space::0","time":{"start":1749744347725,"stop":1749744348325,"duration":600},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"labels":[{"name":"tag","value":"backend"},{"name":"parentSuite","value":"tests.test_backend.project"},{"name":"suite","value":"test_project"},{"name":"host","value":"pkrvmxyh4eaekms"},{"name":"thread","value":"2546-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_backend.project.test_project"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"history":{"statistic":{"failed":0,"broken":7,"skipped":0,"passed":2,"unknown":0,"total":9},"items":[{"uid":"8fdb01e222e86581","reportUrl":"https://vaizcom.github.io/autotests/123//#testresult/8fdb01e222e86581","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f6ed7455e50>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749744006292,"stop":1749744006292,"duration":0}},{"uid":"f9b2a0cb9f07608f","reportUrl":"https://vaizcom.github.io/autotests/122//#testresult/f9b2a0cb9f07608f","status":"passed","time":{"start":1749743643000,"stop":1749743643204,"duration":204}},{"uid":"28544b3ea300c0f3","reportUrl":"https://vaizcom.github.io/autotests/119//#testresult/28544b3ea300c0f3","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc7b5913490>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749742823327,"stop":1749742823327,"duration":0}},{"uid":"c5bb142e7eb86e44","reportUrl":"https://vaizcom.github.io/autotests/118//#testresult/c5bb142e7eb86e44","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f9cb88f1f10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749742670834,"stop":1749742670834,"duration":0}},{"uid":"762b490141e06a39","reportUrl":"https://vaizcom.github.io/autotests/117//#testresult/762b490141e06a39","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2b9f21f250>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749742500609,"stop":1749742500609,"duration":0}},{"uid":"154c15b19e87ecdd","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/154c15b19e87ecdd","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741236963,"stop":1749741236963,"duration":0}},{"uid":"d94b9fa3ce10a238","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/d94b9fa3ce10a238","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740829629,"stop":1749740829629,"duration":0}},{"uid":"d562fa9874c2de3e","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/d562fa9874c2de3e","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740656241,"stop":1749740656241,"duration":0}}]},"tags":["backend"]},"source":"98c1e5824a231cdf.json","parameterValues":[]}